# source: https://github.com/briancappello/flask-unchained-react-spa/blob/master/docker-compose.yaml
---
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888  # access the app at localhost:8888
      - 5555:5555  # access webpack bundle analyzer at localhost:5555
    environment:
      - API_HOST=backend
      - API_PORT=5000
    entrypoint:
      - /frontend-entrypoint.sh
    volumes:
      - ./frontend:/flask/frontend
